<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TelemetrySeeder extends Seeder
{

    public function run(): void
    {
        DB::table('telemetries')->insert([
            [
                'time' => Carbon::parse('2025-04-01 08:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '22.5°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.2V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-02 10:15:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Lost',
                'sensor_thermal' => '85.1°C',
                'sensor_payload' => 'Inactive',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Booting',
                'sensor_power' => '22.9V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-03 14:45:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '95.0°C',
                'sensor_payload' => 'Failure',
                'sensor_control' => 'Unresponsive',
                'sensor_obc' => 'Crashed',
                'sensor_power' => '0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-04 12:30:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '21.8°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.5V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-05 11:00:00'),
                'sensor_telemetry' => 'Intermittent',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '65.0°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '25.1V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-06 09:20:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '23.3°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.0V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-07 15:30:00'),
                'sensor_telemetry' => 'Failure',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '99.2°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-08 13:10:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.7°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.9V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-09 07:50:00'),
                'sensor_telemetry' => 'Degraded',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '70.4°C',
                'sensor_payload' => 'Low Power',
                'sensor_control' => 'Slow Response',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '23.0V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-10 18:25:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '102.8°C',
                'sensor_payload' => 'Failure',
                'sensor_control' => 'Stuck',
                'sensor_obc' => 'Dead',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-21 08:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '26.0°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.4V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-22 10:10:00'),
                'sensor_telemetry' => 'Intermittent',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Laggy',
                'sensor_thermal' => '70.2°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '24.7V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-23 13:15:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '102.0°C',
                'sensor_payload' => 'Failure',
                'sensor_control' => 'Unresponsive',
                'sensor_obc' => 'Dead',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-24 11:45:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.9°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.0V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-25 14:30:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '75.6°C',
                'sensor_payload' => 'Low Power',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.0V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-26 12:50:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '23.4°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.6V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-27 09:25:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '99.9°C',
                'sensor_payload' => 'Failure',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-28 15:10:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '25.5°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.1V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-29 07:30:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '73.3°C',
                'sensor_payload' => 'Inactive',
                'sensor_control' => 'Laggy',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '24.9V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-30 16:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '110.2°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-11 08:40:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '25.0°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.1V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-12 09:05:00'),
                'sensor_telemetry' => 'Intermittent',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '67.3°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Reinitializing',
                'sensor_power' => '24.5V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-13 16:45:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '100.0°C',
                'sensor_payload' => 'Failure',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Dead',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-14 13:35:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '23.8°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.7V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-15 07:20:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Laggy',
                'sensor_thermal' => '72.0°C',
                'sensor_payload' => 'Inactive',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '23.5V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-16 10:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.1°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.3V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-17 12:30:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '105.0°C',
                'sensor_payload' => 'Failure',
                'sensor_control' => 'Unresponsive',
                'sensor_obc' => 'Crashed',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-18 14:15:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '25.4°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.8V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-19 09:55:00'),
                'sensor_telemetry' => 'Degraded',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '76.5°C',
                'sensor_payload' => 'Low Power',
                'sensor_control' => 'Slow',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '24.2V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-20 11:40:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '101.1°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-11 08:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.4°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.6V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-12 09:15:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '70.1°C',
                'sensor_payload' => 'Idle',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '24.1V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-13 10:30:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '102.3°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-14 11:45:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '25.0°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.1V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-15 13:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '67.4°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '25.9V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-16 14:15:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '99.8°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-17 15:30:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '26.0°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.5V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-18 16:45:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '69.3°C',
                'sensor_payload' => 'Idle',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.0V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-19 18:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '110.0°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-20 19:15:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.0°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.0V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-01 08:40:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.6°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.8V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-02 12:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '69.5°C',
                'sensor_payload' => 'Idle',
                'sensor_control' => 'Slow',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.3V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-03 10:25:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '95.2°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-04 14:15:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '23.8°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.0V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-05 09:30:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '71.1°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '24.5V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-06 13:45:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '25.2°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '28.3V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-07 11:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '105.5°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-21 08:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '65.3°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '24.7V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-22 09:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '101.6°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-23 10:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '23.5°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.8V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-24 11:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '68.9°C',
                'sensor_payload' => 'Idle',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.2V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-25 12:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '98.5°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-26 13:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '25.6°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.2V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-27 14:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '66.0°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.7V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-28 15:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '100.7°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-29 16:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.2°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.5V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-04-30 17:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '69.5°C',
                'sensor_payload' => 'Idle',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '25.3V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-01 08:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '25.1°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.3V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-02 09:30:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '63.4°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.5V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-03 10:45:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '97.8°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-04 11:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '23.9°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.6V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-05 12:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '66.7°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.9V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-06 13:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '95.2°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-07 14:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '22.3°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.0V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-08 15:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '69.2°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Resetting',
                'sensor_power' => '25.4V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-09 16:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '100.3°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-10 17:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '24.6°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.4V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-11 18:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '73.8°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.3V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-12 19:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '98.7°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-13 20:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '21.9°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.2V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-14 21:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '65.4°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.8V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-15 22:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '94.2°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-16 23:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '23.2°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.5V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-17 00:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Unstable',
                'sensor_thermal' => '61.5°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Lagging',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.6V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-18 01:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '99.9°C',
                'sensor_payload' => 'Error',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-19 02:00:00'),
                'sensor_telemetry' => 'Nominal',
                'sensor_gps' => 'Locked',
                'sensor_communication' => 'Stable',
                'sensor_thermal' => '22.4°C',
                'sensor_payload' => 'Active',
                'sensor_control' => 'Responsive',
                'sensor_obc' => 'Operational',
                'sensor_power' => '27.1V',
                'status' => 'Valid',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-20 03:00:00'),
                'sensor_telemetry' => 'Warning',
                'sensor_gps' => 'Searching',
                'sensor_communication' => 'Fluctuating',
                'sensor_thermal' => '64.8°C',
                'sensor_payload' => 'Standby',
                'sensor_control' => 'Delayed',
                'sensor_obc' => 'Rebooting',
                'sensor_power' => '25.1V',
                'status' => 'Incomplete',
                'subsystem_name' => 'Telemetry',
            ],
            [
                'time' => Carbon::parse('2025-05-21 04:00:00'),
                'sensor_telemetry' => 'Critical',
                'sensor_gps' => 'No Signal',
                'sensor_communication' => 'Offline',
                'sensor_thermal' => '97.1°C',
                'sensor_payload' => 'Failing',
                'sensor_control' => 'Frozen',
                'sensor_obc' => 'Shutdown',
                'sensor_power' => '0.0V',
                'status' => 'Error',
                'subsystem_name' => 'Telemetry',
            ],
        ]);
    }
}

