<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ThermalSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('thermals')->insert([
            [
                'telemetry_id' => 71,
                'time' => Carbon::parse('2025-05-21 08:00:00'),
                'internal_temperature' => 22.5,
                'external_temperature' => -75.0,
                'battery_temperature' => 15.0,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
            [
                'telemetry_id' => 72,
                'time' => Carbon::parse('2025-05-22 09:00:00'),
                'internal_temperature' => 24.0,
                'external_temperature' => -70.0,
                'battery_temperature' => 16.5,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
            [
                'telemetry_id' => 73,
                'time' => Carbon::parse('2025-05-23 10:00:00'),
                'internal_temperature' => 26.0,
                'external_temperature' => -65.0,
                'battery_temperature' => 17.0,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
            [
                'telemetry_id' => 74,
                'time' => Carbon::parse('2025-05-24 11:00:00'),
                'internal_temperature' => 28.0,
                'external_temperature' => -60.0,
                'battery_temperature' => 18.0,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
            [
                'telemetry_id' => 75,
                'time' => Carbon::parse('2025-05-25 12:00:00'),
                'internal_temperature' => 30.0,
                'external_temperature' => -55.0,
                'battery_temperature' => 19.0,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
            [
                'telemetry_id' => 76,
                'time' => Carbon::parse('2025-05-26 13:00:00'),
                'internal_temperature' => 32.0,
                'external_temperature' => -50.0,
                'battery_temperature' => 20.0,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
            [
                'telemetry_id' => 77,
                'time' => Carbon::parse('2025-05-27 14:00:00'),
                'internal_temperature' => 34.0,
                'external_temperature' => -45.0,
                'battery_temperature' => 21.0,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
            [
                'telemetry_id' => 78,
                'time' => Carbon::parse('2025-05-28 15:00:00'),
                'internal_temperature' => 36.0,
                'external_temperature' => -40.0,
                'battery_temperature' => 22.0,
                'cooling_status' => 'Active',
                'radiator_status' => 1,
                'thermal_alert' => 0,
                'subsystem_name' => 'Thermal Control',
            ],
                [
                    'telemetry_id' => 21,
                    'time' => Carbon::parse('2025-06-19 22:25:00'),
                    'internal_temperature' => 108.0,
                    'external_temperature' => -109.3,
                    'battery_temperature' => 79.1,
                    'cooling_status' => 'Failed',
                    'radiator_status' => 0,
                    'thermal_alert' => 1,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 22,
                    'time' => Carbon::parse('2025-06-20 23:15:00'),
                    'internal_temperature' => 110.5,
                    'external_temperature' => -107.4,
                    'battery_temperature' => 81.2,
                    'cooling_status' => 'Standby',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 23,
                    'time' => Carbon::parse('2025-06-21 00:45:00'),
                    'internal_temperature' => 113.2,
                    'external_temperature' => -105.6,
                    'battery_temperature' => 83.3,
                    'cooling_status' => 'Active',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 24,
                    'time' => Carbon::parse('2025-06-22 01:10:00'),
                    'internal_temperature' => 115.8,
                    'external_temperature' => -102.5,
                    'battery_temperature' => 85.0,
                    'cooling_status' => 'Failed',
                    'radiator_status' => 1,
                    'thermal_alert' => 1,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 25,
                    'time' => Carbon::parse('2025-06-23 02:00:00'),
                    'internal_temperature' => 118.4,
                    'external_temperature' => -100.7,
                    'battery_temperature' => 87.5,
                    'cooling_status' => 'Standby',
                    'radiator_status' => 0,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 26,
                    'time' => Carbon::parse('2025-06-24 03:30:00'),
                    'internal_temperature' => 120.7,
                    'external_temperature' => -98.4,
                    'battery_temperature' => 89.0,
                    'cooling_status' => 'Active',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 27,
                    'time' => Carbon::parse('2025-06-25 04:50:00'),
                    'internal_temperature' => 123.2,
                    'external_temperature' => -101.8,
                    'battery_temperature' => 91.3,
                    'cooling_status' => 'Failed',
                    'radiator_status' => 0,
                    'thermal_alert' => 1,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 28,
                    'time' => Carbon::parse('2025-06-26 05:15:00'),
                    'internal_temperature' => 125.5,
                    'external_temperature' => -104.1,
                    'battery_temperature' => 93.5,
                    'cooling_status' => 'Standby',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 29,
                    'time' => Carbon::parse('2025-06-27 06:30:00'),
                    'internal_temperature' => 128.1,
                    'external_temperature' => -99.2,
                    'battery_temperature' => 95.0,
                    'cooling_status' => 'Active',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 30,
                    'time' => Carbon::parse('2025-06-28 07:10:00'),
                    'internal_temperature' => 130.7,
                    'external_temperature' => -98.8,
                    'battery_temperature' => 97.4,
                    'cooling_status' => 'Failed',
                    'radiator_status' => 0,
                    'thermal_alert' => 1,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 31,
                    'time' => Carbon::parse('2025-06-29 08:00:00'),
                    'internal_temperature' => 133.2,
                    'external_temperature' => -102.0,
                    'battery_temperature' => 99.0,
                    'cooling_status' => 'Standby',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 32,
                    'time' => Carbon::parse('2025-06-30 09:25:00'),
                    'internal_temperature' => 135.3,
                    'external_temperature' => -99.4,
                    'battery_temperature' => 101.2,
                    'cooling_status' => 'Active',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 33,
                    'time' => Carbon::parse('2025-07-01 10:00:00'),
                    'internal_temperature' => 138.0,
                    'external_temperature' => -97.5,
                    'battery_temperature' => 103.5,
                    'cooling_status' => 'Failed',
                    'radiator_status' => 0,
                    'thermal_alert' => 1,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 34,
                    'time' => Carbon::parse('2025-07-02 11:30:00'),
                    'internal_temperature' => 140.2,
                    'external_temperature' => -94.7,
                    'battery_temperature' => 105.6,
                    'cooling_status' => 'Standby',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 35,
                    'time' => Carbon::parse('2025-07-03 12:00:00'),
                    'internal_temperature' => 142.6,
                    'external_temperature' => -96.9,
                    'battery_temperature' => 107.8,
                    'cooling_status' => 'Active',
                    'radiator_status' => 0,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 36,
                    'time' => Carbon::parse('2025-07-04 13:15:00'),
                    'internal_temperature' => 145.0,
                    'external_temperature' => -99.1,
                    'battery_temperature' => 110.2,
                    'cooling_status' => 'Failed',
                    'radiator_status' => 1,
                    'thermal_alert' => 1,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 37,
                    'time' => Carbon::parse('2025-07-05 14:45:00'),
                    'internal_temperature' => 147.5,
                    'external_temperature' => -102.8,
                    'battery_temperature' => 112.0,
                    'cooling_status' => 'Standby',
                    'radiator_status' => 0,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 38,
                    'time' => Carbon::parse('2025-07-06 15:25:00'),
                    'internal_temperature' => 150.0,
                    'external_temperature' => -100.0,
                    'battery_temperature' => 114.5,
                    'cooling_status' => 'Active',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 39,
                    'time' => Carbon::parse('2025-07-07 16:30:00'),
                    'internal_temperature' => 152.3,
                    'external_temperature' => -104.4,
                    'battery_temperature' => 116.7,
                    'cooling_status' => 'Failed',
                    'radiator_status' => 0,
                    'thermal_alert' => 1,
                    'subsystem_name' => 'Thermal',
                ],
                [
                    'telemetry_id' => 40,
                    'time' => Carbon::parse('2025-07-08 17:00:00'),
                    'internal_temperature' => 154.8,
                    'external_temperature' => -106.3,
                    'battery_temperature' => 119.0,
                    'cooling_status' => 'Standby',
                    'radiator_status' => 1,
                    'thermal_alert' => 0,
                    'subsystem_name' => 'Thermal',
                ],
                    [
                        'telemetry_id' => 2,
                        'time' => Carbon::parse('2025-05-31 03:15:00'),
                        'internal_temperature' => 65.2,
                        'external_temperature' => -100.5,
                        'battery_temperature' => 42.8,
                        'cooling_status' => 'Active',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 3,
                        'time' => Carbon::parse('2025-06-01 04:00:00'),
                        'internal_temperature' => 67.3,
                        'external_temperature' => -110.3,
                        'battery_temperature' => 44.0,
                        'cooling_status' => 'Failed',
                        'radiator_status' => 0,
                        'thermal_alert' => 1,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 4,
                        'time' => Carbon::parse('2025-06-02 05:25:00'),
                        'internal_temperature' => 70.1,
                        'external_temperature' => -97.8,
                        'battery_temperature' => 45.3,
                        'cooling_status' => 'Standby',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 5,
                        'time' => Carbon::parse('2025-06-03 06:45:00'),
                        'internal_temperature' => 72.6,
                        'external_temperature' => -103.6,
                        'battery_temperature' => 47.1,
                        'cooling_status' => 'Active',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 6,
                        'time' => Carbon::parse('2025-06-04 07:55:00'),
                        'internal_temperature' => 75.0,
                        'external_temperature' => -108.0,
                        'battery_temperature' => 49.5,
                        'cooling_status' => 'Failed',
                        'radiator_status' => 0,
                        'thermal_alert' => 1,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 7,
                        'time' => Carbon::parse('2025-06-05 08:20:00'),
                        'internal_temperature' => 78.3,
                        'external_temperature' => -101.9,
                        'battery_temperature' => 51.2,
                        'cooling_status' => 'Standby',
                        'radiator_status' => 0,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 8,
                        'time' => Carbon::parse('2025-06-06 09:10:00'),
                        'internal_temperature' => 80.5,
                        'external_temperature' => -99.2,
                        'battery_temperature' => 53.0,
                        'cooling_status' => 'Active',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 9,
                        'time' => Carbon::parse('2025-06-07 10:30:00'),
                        'internal_temperature' => 83.0,
                        'external_temperature' => -95.4,
                        'battery_temperature' => 54.3,
                        'cooling_status' => 'Failed',
                        'radiator_status' => 1,
                        'thermal_alert' => 1,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 10,
                        'time' => Carbon::parse('2025-06-08 11:00:00'),
                        'internal_temperature' => 85.1,
                        'external_temperature' => -104.5,
                        'battery_temperature' => 56.1,
                        'cooling_status' => 'Standby',
                        'radiator_status' => 0,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 11,
                        'time' => Carbon::parse('2025-06-09 12:25:00'),
                        'internal_temperature' => 88.0,
                        'external_temperature' => -111.2,
                        'battery_temperature' => 58.2,
                        'cooling_status' => 'Active',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 12,
                        'time' => Carbon::parse('2025-06-10 13:45:00'),
                        'internal_temperature' => 90.4,
                        'external_temperature' => -113.6,
                        'battery_temperature' => 60.3,
                        'cooling_status' => 'Failed',
                        'radiator_status' => 1,
                        'thermal_alert' => 1,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 13,
                        'time' => Carbon::parse('2025-06-11 14:20:00'),
                        'internal_temperature' => 92.6,
                        'external_temperature' => -107.9,
                        'battery_temperature' => 62.0,
                        'cooling_status' => 'Standby',
                        'radiator_status' => 0,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 14,
                        'time' => Carbon::parse('2025-06-12 15:35:00'),
                        'internal_temperature' => 94.3,
                        'external_temperature' => -95.1,
                        'battery_temperature' => 64.7,
                        'cooling_status' => 'Active',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 15,
                        'time' => Carbon::parse('2025-06-13 16:10:00'),
                        'internal_temperature' => 96.0,
                        'external_temperature' => -101.5,
                        'battery_temperature' => 67.2,
                        'cooling_status' => 'Failed',
                        'radiator_status' => 0,
                        'thermal_alert' => 1,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 16,
                        'time' => Carbon::parse('2025-06-14 17:25:00'),
                        'internal_temperature' => 98.1,
                        'external_temperature' => -105.2,
                        'battery_temperature' => 68.9,
                        'cooling_status' => 'Standby',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 17,
                        'time' => Carbon::parse('2025-06-15 18:00:00'),
                        'internal_temperature' => 100.0,
                        'external_temperature' => -110.8,
                        'battery_temperature' => 71.1,
                        'cooling_status' => 'Active',
                        'radiator_status' => 0,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 18,
                        'time' => Carbon::parse('2025-06-16 19:30:00'),
                        'internal_temperature' => 102.3,
                        'external_temperature' => -113.0,
                        'battery_temperature' => 73.4,
                        'cooling_status' => 'Failed',
                        'radiator_status' => 1,
                        'thermal_alert' => 1,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 19,
                        'time' => Carbon::parse('2025-06-17 20:45:00'),
                        'internal_temperature' => 104.5,
                        'external_temperature' => -104.2,
                        'battery_temperature' => 75.6,
                        'cooling_status' => 'Standby',
                        'radiator_status' => 0,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                    [
                        'telemetry_id' => 20,
                        'time' => Carbon::parse('2025-06-18 21:10:00'),
                        'internal_temperature' => 106.7,
                        'external_temperature' => -106.9,
                        'battery_temperature' => 77.3,
                        'cooling_status' => 'Active',
                        'radiator_status' => 1,
                        'thermal_alert' => 0,
                        'subsystem_name' => 'Thermal',
                    ],
                        [
                            'telemetry_id' => 71,
                            'time' => Carbon::parse('2025-05-21 17:05:00'),
                            'internal_temperature' => 40.4,
                            'external_temperature' => -106.8,
                            'battery_temperature' => 25.4,
                            'cooling_status' => 'Active',
                            'radiator_status' => 1,
                            'thermal_alert' => 0,
                            'subsystem_name' => 'Thermal',
                        ],
                        [
                            'telemetry_id' => 72,
                            'time' => Carbon::parse('2025-05-22 18:25:00'),
                            'internal_temperature' => 42.1,
                            'external_temperature' => -102.4,
                            'battery_temperature' => 26.7,
                            'cooling_status' => 'Failed',
                            'radiator_status' => 0,
                            'thermal_alert' => 1,
                            'subsystem_name' => 'Thermal',
                        ],
                        [
                            'telemetry_id' => 73,
                            'time' => Carbon::parse('2025-05-23 19:40:00'),
                            'internal_temperature' => 45.3,
                            'external_temperature' => -99.1,
                            'battery_temperature' => 28.1,
                            'cooling_status' => 'Standby',
                            'radiator_status' => 0,
                            'thermal_alert' => 0,
                            'subsystem_name' => 'Thermal',
                        ],
                        [
                            'telemetry_id' => 74,
                            'time' => Carbon::parse('2025-05-24 20:55:00'),
                            'internal_temperature' => 48.0,
                            'external_temperature' => -104.2,
                            'battery_temperature' => 30.5,
                            'cooling_status' => 'Active',
                            'radiator_status' => 1,
                            'thermal_alert' => 0,
                            'subsystem_name' => 'Thermal',
                        ],
                        [
                            'telemetry_id' => 75,
                            'time' => Carbon::parse('2025-05-25 21:10:00'),
                            'internal_temperature' => 50.3,
                            'external_temperature' => -112.7,
                            'battery_temperature' => 32.0,
                            'cooling_status' => 'Failed',
                            'radiator_status' => 0,
                            'thermal_alert' => 1,
                            'subsystem_name' => 'Thermal',
                        ],
                        [
                            'telemetry_id' => 76,
                            'time' => Carbon::parse('2025-05-26 22:15:00'),
                            'internal_temperature' => 52.8,
                            'external_temperature' => -95.5,
                            'battery_temperature' => 34.2,
                            'cooling_status' => 'Active',
                            'radiator_status' => 1,
                            'thermal_alert' => 0,
                            'subsystem_name' => 'Thermal',
                        ],
                        [
                            'telemetry_id' => 77,
                            'time' => Carbon::parse('2025-05-27 23:00:00'),
                            'internal_temperature' => 55.0,
                            'external_temperature' => -108.9,
                            'battery_temperature' => 35.5,
                            'cooling_status' => 'Standby',
                            'radiator_status' => 1,
                            'thermal_alert' => 0,
                            'subsystem_name' => 'Thermal',
                        ],
                        [
                            'telemetry_id' => 78,
                            'time' => Carbon::parse('2025-05-28 00:20:00'),
                            'internal_temperature' => 58.2,
                            'external_temperature' => -99.0,
                            'battery_temperature' => 37.8,
                            'cooling_status' => 'Failed',
                            'radiator_status' => 0,
                            'thermal_alert' => 1,
                            'subsystem_name' => 'Thermal',
                        ],
            
                    
        ]);
    }
}
